name: Generate Snake

on:
  schedule:
      - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: aman23-cmd
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
